<?php

define('SOKEIO_URL_ADMIN', 'SOKEIO_URL_ADMIN');
define('SOKEIO_URL_LOGIN', 'SOKEIO_URL_LOGIN');
define('SOKEIO_IS_ADMIN', 'SOKEIO_IS_ADMIN');

define('PLATFORM_SITE_NAME', 'PLATFORM_SITE_NAME');
define('PLATFORM_SITE_DESCRIPTION', 'PLATFORM_SITE_DESCRIPTION');

define('PLATFORM_THEME_LAYOUT', 'PLATFORM_THEME_LAYOUT');
define('PLATFORM_THEME_CLASS', 'PLATFORM_THEME_CLASS');
define('PLATFORM_THEME_ADMIN', 'PLATFORM_THEME_ADMIN');
define('PLATFORM_THEME_WEB', 'PLATFORM_THEME_WEB');
define('PLATFORM_THEME_FILTER_LAYOUT', 'PLATFORM_THEME_FILTER_LAYOUT');

define('PLATFORM_CONFIG_JS', 'PLATFORM_CONFIG_JS');
define('PLATFORM_DO_COMPONENT', 'PLATFORM_DO_COMPONENT');
define('PLATFORM_DO_EVENT', 'PLATFORM_DO_EVENT');
define('PLATFORM_DO_WEBHOOK', 'PLATFORM_DO_WEBHOOK');
define('PLATFORM_MODEL_LIST', 'PLATFORM_MODEL_LIST');



define('PLATFORM_MIDDLEWARE_API', 'PLATFORM_MIDDLEWARE_API');
define('PLATFORM_MIDDLEWARE_WEB', 'PLATFORM_MIDDLEWARE_WEB');
define('PLATFORM_MIDDLEWARE_ADMIN', 'PLATFORM_MIDDLEWARE_ADMIN');

define('PLATFORM_MIDDLEWARE_BEFORE', 'PLATFORM_MIDDLEWARE_BEFORE');
define('PLATFORM_MIDDLEWARE_AFTER', 'PLATFORM_MIDDLEWARE_AFTER');
define('PLATFORM_MIDDLEWARE_API_BEFORE', 'PLATFORM_MIDDLEWARE_API_BEFORE');
define('PLATFORM_MIDDLEWARE_API_AFTER', 'PLATFORM_MIDDLEWARE_API_AFTER');


define('PLATFORM_ROLE_SUPPER_ADMIN', 'PLATFORM_ROLE_SUPPER_ADMIN');
define('PLATFORM_PERMISSION_IGNORE', 'PLATFORM_PERMISSION_IGNORE');
define('PLATFORM_PERMISSION_CUSTOME', 'PLATFORM_PERMISSION_CUSTOME');
define('PLATFORM_CHECK_ROLE', 'PLATFORM_CHECK_ROLE');
define('PLATFORM_CHECK_PERMISSION', 'PLATFORM_CHECK_PERMISSION');


define('PLATFORM_HEAD_BEFORE', 'PLATFORM_HEAD_BEFORE');
define('PLATFORM_HEAD_AFTER', 'PLATFORM_HEAD_AFTER');

define('PLATFORM_BODY_BEFORE', 'PLATFORM_BODY_BEFORE');
define('PLATFORM_BODY_AFTER', 'PLATFORM_BODY_AFTER');

define('PLATFORM_EXCEPTIONS_HANDLER', 'PLATFORM_EXCEPTIONS_HANDLER');

define('PLATFORM_HOMEPAGE', 'PLATFORM_HOMEPAGE');
