<?php

define('PLATFORM_THEME_LAYOUT', 'PLATFORM_THEME_LAYOUT');
define('PLATFORM_THEME_CLASS', 'PLATFORM_THEME_CLASS');
define('PLATFORM_THEME_ADMIN', 'PLATFORM_THEME_ADMIN');
define('PLATFORM_THEME_WEB', 'PLATFORM_THEME_WEB');
define('PLATFORM_THEME_FILTER_LAYOUT', 'PLATFORM_THEME_FILTER_LAYOUT');
define('BYTE_URL_ADMIN', 'BYTE_URL_ADMIN');
define('PLATFORM_URL_LOGIN', 'PLATFORM_URL_LOGIN');
define('PLATFORM_PAGE_TITLE', 'PLATFORM_PAGE_TITLE');
define('PLATFORM_CONFIG_JS', 'PLATFORM_CONFIG_JS');
define('PLATFORM_DO_COMPONENT', 'PLATFORM_DO_COMPONENT');
define('PLATFORM_DO_EVENT', 'PLATFORM_DO_EVENT');
define('PLATFORM_DO_WEBHOOK', 'PLATFORM_DO_WEBHOOK');
define('PLATFORM_IS_ADMIN', 'PLATFORM_IS_ADMIN');
define('PLATFORM_LOAD_THEME_ROUTE_MATCHED', 'PLATFORM_LOAD_THEME_ROUTE_MATCHED');
define('PLATFORM_MODEL_LIST', 'PLATFORM_MODEL_LIST');



define('PLATFORM_MIDDLEWARE_API', 'PLATFORM_MIDDLEWARE_API');
define('PLATFORM_MIDDLEWARE_WEB', 'PLATFORM_MIDDLEWARE_WEB');
define('PLATFORM_MIDDLEWARE_ADMIN', 'PLATFORM_MIDDLEWARE_ADMIN');

define('PLATFORM_MIDDLEWARE_BEFORE', 'PLATFORM_MIDDLEWARE_BEFORE');
define('PLATFORM_MIDDLEWARE_AFTER', 'PLATFORM_MIDDLEWARE_AFTER');
define('PLATFORM_MIDDLEWARE_API_BEFORE', 'PLATFORM_MIDDLEWARE_API_BEFORE');
define('PLATFORM_MIDDLEWARE_API_AFTER', 'PLATFORM_MIDDLEWARE_API_AFTER');


define('PLATFORM_ROLE_SUPPER_ADMIN', 'PLATFORM_ROLE_SUPPER_ADMIN');
define('PLATFORM_CHECK_PERMISSION', 'PLATFORM_CHECK_PERMISSION');
define('PLATFORM_PERMISSION_IGNORE', 'PLATFORM_PERMISSION_IGNORE');
define('PLATFORM_CHECK_ROLE', 'PLATFORM_CHECK_ROLE');
define('PLATFORM_PERMISSION_CUSTOME', 'PLATFORM_PERMISSION_CUSTOME');


define('PLATFORM_HEAD_BEFORE', 'PLATFORM_HEAD_BEFORE');
define('PLATFORM_HEAD_AFTER', 'PLATFORM_HEAD_AFTER');
define('PLATFORM_BODY_BEFORE', 'PLATFORM_BODY_BEFORE');
define('PLATFORM_BODY_AFTER', 'PLATFORM_BODY_AFTER');

define('PLATFORM_EXCEPTIONS_HANDLER', 'PLATFORM_EXCEPTIONS_HANDLER');

define('PLATFORM_HOMEPAGE', 'PLATFORM_HOMEPAGE');

define('PLATFORM_LOGIN_PAGE_AFTER', 'PLATFORM_LOGIN_PAGE_AFTER');
define('PLATFORM_REGISTER_PAGE_AFTER', 'PLATFORM_REGISTER_PAGE_AFTER');



define('PLATFORM_FORM_RENDER', 'PLATFORM_FORM_RENDER');
define('PLATFORM_FIELD_RENDER', 'PLATFORM_FIELD_RENDER');
define('PLATFORM_TABLE_RENDER', 'PLATFORM_TABLE_RENDER');
